using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MasafiFleetSync.API.Models
{
    public class Trip
    {
        [Key]
        public int Id { get; set; }

        // --- CRITICAL ARCHITECTURAL FIX: Direct link to originating water order request ---
        [Required]
        public int WaterOrderId { get; set; }

        [ForeignKey("WaterOrderId")]
        public WaterOrder? WaterOrder { get; set; } // Prevents data division across accounting ledgers

        [Required]
        public int CustomerId { get; set; } // Link to the User/Customer who placed the water order

        [Required]
        public int VehicleId { get; set; } // Link to assigned Tanker/Truck asset

        [Required]
        public int DriverId { get; set; } // Link to assigned Driver entity

        [Required]
        [StringLength(150)]
        public string StartLocation { get; set; } = string.Empty;

        [Required]
        [StringLength(150)]
        public string Destination { get; set; } = string.Empty;

        [Required]
        public double OptimizedDistanceKm { get; set; } // Distance calculated by Google Maps API / VRP logic

        public double? ActualDistanceKm { get; set; } // Recorded upon actual delivery completion

        [Required]
        public int GallonsDelivered { get; set; } // Crucial water asset volume tracking for Al-Waqar Transport specifications

        // --- Financial & Driver Earnings Segment ---
        [Required]
        [Column(TypeName = "decimal(18,2)")]
        public decimal TotalDeliveryFare { get; set; } // Base financial tracking generated by distance pricing formulas

        [Required]
        [Column(TypeName = "decimal(18,2)")]
        public decimal CommissionDeduction { get; set; } // Auto-calculated company deduction chunk

        [Required]
        [Column(TypeName = "decimal(18,2)")]
        public decimal NetDriverEarnings { get; set; } // Driver's final take-home payout from the route split

        // --- Telemetry Monitoring ---
        public double? CurrentDriverLatitude { get; set; } // Supports mandatory real-time dashboard map views (Screen 8 Background tasks)
        public double? CurrentDriverLongitude { get; set; }

        [Required]
        [StringLength(30)]
        public string Status { get; set; } = "Scheduled"; // Scheduled, In Transit, Delayed, Completed, Cancelled

        [Required]
        public DateTime ScheduledStart { get; set; }

        public DateTime? ActualStart { get; set; }

        public DateTime? ActualEnd { get; set; }
    }
}